### Getting Names of text files from row_files Folder

In [42]:
import os

# folder path
dir_path = r'E:\OneDrive\Desktop\NLP_Task#1\row_files'

# list to store files
res = []

# Iterate directory
for path in os.listdir(dir_path):
    # check if current path is a file
    if os.path.isfile(os.path.join(dir_path, path)):
        res.append(path)
print(res)

['.DS_Store', '0169.2002-05-13.SA_and_HP.spam.txt', '0390.2002-05-29.SA_and_HP.spam.txt', '0405.2002-05-31.SA_and_HP.spam.txt', '0438.2002-06-04.SA_and_HP.spam.txt', '0571.2002-06-24.SA_and_HP.spam.txt', '0824.2002-07-23.SA_and_HP.spam.txt', '0892.2002-07-24.SA_and_HP.spam.txt', '0946.2002-07-25.SA_and_HP.spam.txt', '1218.2002-08-23.SA_and_HP.spam.txt', '1580.2002-12-03.SA_and_HP.spam.txt', '1861.2005-06-22.SA_and_HP.spam.txt', '1971.2005-06-22.SA_and_HP.spam.txt', '2041.2005-06-22.SA_and_HP.spam.txt', '2441.2005-06-25.SA_and_HP.spam.txt', '2720.2005-06-27.SA_and_HP.spam.txt', '2886.2005-06-28.SA_and_HP.spam.txt', '3418.2005-07-01.SA_and_HP.spam.txt', '4010.2005-07-05.SA_and_HP.spam.txt', '5009.2005-07-18.SA_and_HP.spam.txt', '5225.2005-07-19.SA_and_HP.spam.txt', '5242.2005-07-19.SA_and_HP.spam.txt', '5277.2005-07-19.SA_and_HP.spam.txt', 'file.txt', 'Untitled.ipynb']

### Merging all the text files data into single file

In [146]:
import pandas as pd
data = pd.read_csv('input.csv', encoding="latin1")
data.head()

    Sentence #           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

In [147]:
data =data.fillna(method ="ffill")
data

              Sentence #           Word  POS Tag
0            Sentence: 1      Thousands  NNS   O
1            Sentence: 1             of   IN   O
2            Sentence: 1  demonstrators  NNS   O
3            Sentence: 1           have  VBP   O
4            Sentence: 1        marched  VBN   O
...                  ...            ...  ...  ..
1048570  Sentence: 47959           they  PRP   O
1048571  Sentence: 47959      responded  VBD   O
1048572  Sentence: 47959             to   TO   O
1048573  Sentence: 47959            the   DT   O
1048574  Sentence: 47959         attack   NN   O

[1048575 rows x 4 columns]

In [41]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [203]:
data["sentence_id"] = LabelEncoder().fit_transform(data["sentence_id"] )
data.head(30)

    sentence_id          words  POS labels
0             0      Thousands  NNS      O
1             0             of   IN      O
2             0  demonstrators  NNS      O
3             0           have  VBP      O
4             0        marched  VBN      O
5             0        through   IN      O
6             0         London  NNP  B-GEO
7             0             to   TO      O
8             0        protest   VB      O
9             0            the   DT      O
10            0            war   NN      O
11            0             in   IN      O
12            0           Iraq  NNP  B-GEO
13            0            and   CC      O
14            0         demand   VB      O
15            0            the   DT      O
16            0     withdrawal   NN      O
17            0             of   IN      O
18            0        British   JJ  B-GPE
19            0         troops  NNS      O
20            0           from   IN      O
21            0           that   DT      O
22            0        country   NN      O
23            0              .    .      O
24        11111       Families  NNS      O
25        11111             of   IN      O
26        11111       soldiers  NNS      O
27        11111         killed  VBN      O
28        11111             in   IN      O
29        11111            the   DT      O

In [199]:
data.rename(columns={"Sentence #":"sentence_id","Word":"words","Tag":"labels"}, inplace =True)

In [200]:
data

         sentence_id          words  POS labels
0                  0      Thousands  NNS      O
1                  0             of   IN      O
2                  0  demonstrators  NNS      O
3                  0           have  VBP      O
4                  0        marched  VBN      O
...              ...            ...  ...    ...
1048570        42177           they  PRP      O
1048571        42177      responded  VBD      O
1048572        42177             to   TO      O
1048573        42177            the   DT      O
1048574        42177         attack   NN      O

[1048575 rows x 4 columns]

In [193]:
data["labels"] = data["labels"].str.upper()

In [9]:
X= data[["sentence_id","words"]]
Y =data["labels"]

In [13]:
from simpletransformers.ner import NERModel,NERArgs

In [15]:
raw_text = ''' 
Subject: attn :
i presume this mail will not be a surprise to you .
i am an accountant with the ministry of mineral
resources and energy in south africa and also a member
of contracts awarding committee of this ministry under
south africa government .
many years ago , south africa government asked this
committee to awards contracts to foreign firms , which
i and 2 of my partners are the leader of this
committee , with our good position , this contracrs
was over invoiced to the tune of us $ 25 , 600 , 000 : 00 as a
deal to be benefit by the three top member of this
committee .
now the contracts value has been paid off to the
actual contractors that executed this jobs , all we
want now is a trusted foreign partner like you that we
shall front with his banking account number to claim
the over inflated sum .
upon our agreemeent to carry on this transaction with
you , the said fund will be share as follows .
75 % will be for us in south africa .
20 % for using your account and other contribution
that might reqiured from you .
5 % is set aside for the up front expences that
will be encounter by both party to get all necessary
documents and formarlities that will justify you as
the rightful owner of this fund .
if you are interested in this transaction , kindly
reply this massege with all your phone and fax
numbers , to enable us furnish you with details and
procedures of this transaction .
god bless you
yours faithfully .
joseph edward .
Subject: turn your paypal account into a non - stop cash machine ! ! ( not a chain letter )
i am sending you this message because we have communicated in the past about business opportunities . i hope you will enjoy this one as much as i do .
turn your paypal account into a non - stop cash machine !
re - occurring 100 % commissions paid directly to your paypal account !
4 out of 10 visitors join instantly !
shouldn ' t you be next ?
did i mention that it ' s free for 15 days ?
simply go to : http : / / www . paypal - profits . com / a / turnkeyim /
best wishes ,
tony & donna scurlock
turnkeyim @ hotmail . com
the best home - based business on the planet ! !
we build your downline - - 1000 to 3500 members added per month ! !
free to join ! !
minimum monthly income ! !
get all the details at :
http : / / www . lifelong - income . com
this email message is sent in compliance with the the 106 th congress e - mail user protection act ( h . r . 1910 ) and the unsolicited commercial electronic mail act of 2000 ( h . r . 3113 ) . though our intention is not to communicate with you again if we receive no response from you , we do provide a valid vehicle for you to be removed from our email list . to be removed from our mailing list , simple reply to this message with remove in the subject line .
please keep in mind that complaints to our email provider and service provider , could make honoring remove requests impossible and you will be in violation of the above legislation .

Subject: re : change of plans
hello you two ,
i am so sorry catherine for not writing recently . i have just been vv busybeing a working mother and sometimes it all gets too much you know ! ! i cannot wait to see you both although we may meet at the airport on the 16 / 6 as that ' s the day we ' re going to france but i will see you both at bronagh ' s house for her 30 th which we ' re going to on the way back from the airport . i am so excited about seeing you ! ! ! liitle eva ( aine ) was born on tuesday
she is absolutely incredible . poor bronagh is 11 dsays over ! !
sounds like you ' ve been having an amazing time . hope you won ' t be too depressed to be back ! !
lots of love
deirdre
" justin mason " wrote :
<
< just a quick note -
<
< we ' ve decided to go up to annapurna base camp instead of
< the jomsom trek - it ' s a bit more impressive visually
< ( if a little soggier ) . so as of tomorrow morning , ourselves
< and our guide bhadra will be leaping like gazelles up 4000 - odd
< metres into the himalayas . . . we ' ll be sure to take a few
< pics on the way . sorry for the bonus mail , but we have to tell
< someone because we forgot to tell the irish embassy ; )
<
< next update in 10 - 14 days , ish ,
<
< - - j .
<
<
<
< _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
< travelogue mailing list
< travelogue @ jmason . org
< http : / / jmason . org / mailman / listinfo / travelogue
<
Subject: don ' t get ripped off ! things to watch out for :
don ' t get ripped off ! gimmicks to look out for :
vacuum pumps : expensive rip - off
most men aren ' t going to wait a whole year to gain 1 " ! ! ! !
or do it the right way , instead they think the more they pump the faster the results . wrong ! a vacuum pump will injure your penis before it will enlarge your penis .
lengthen your manhood the fast , natural way ! check out our new , state of the art
system
weight hanging : dangerous rip - off
only lengthens the penis , does not thicken it , while lessening sensation during intercourse .
and to top it off , it creates unsightly stretching marks , and could cause permanent damage
which could easily require partial amputation of the penis !
obtain a longer , thicker penis without the risks and the pain !
choose the latest scientific breakthroughs , over barbaric tribal techniques
now !
weight hanging : dangerous rip - off
penis enlargement surgery is a very dreaded , painful , and dangerous operation
that has a quite high nonsuccess rate according to patient opinion .
here are just some results .
deformed looking penis ( lumps & pits ) , impotence , loss of sex drive ,
painful erections , if any at all ! !
save your hard earned dollars ! spending more is not always the best solution . obtain a healthy looking , longer penis without scary surgery , and any chance of impotence ! learn more about our amazing exercise techniques !
special offer !

Subject: adv : win a green card and become a u . s citizen !
the united states has a program , called diversity immigrant visa
lottery ( better known as the green card lottery ) , making available
each year by random selection 50 , 000 permanent residence visas
( green cards ) to people from around the world . the objective of the
program is to issue green cards to individuals born in countries with
historically low levels of immigration to the united states .
a green card is a permanent residence visa of the u . s . a . a green card
will give you legal right to work and live permanently in the united
states . green card holders receive health , education , and several other
benefits . if you win a green card , you can apply for u . s . citizenship at
a later time . the green card does not affect your present citizenship .
you and your family could be lucky winners !
your email address was obtained from a purchased list , reference # 00193 . if you wish to unsubscribe
from this list , please click here .
if you have previously unsubscribed and are still receiving this message , you may email our
abuse control center , or call 1 - 888 - 763 - 2497 ,
or write us at : nospam , 6484 coral way , miami , fl , 33155 .
- - - -
this sf . net email is sponsored by : jabber - the world ' s fastest growing
real - time communications platform ! don ' t just im . build it in !
http : / / www . jabber . com / osdn / xim
spamassassin - sightings mailing list

Subject: your commissions of $ 5000 per week ! ssva
give me 5 minutes and i will show you how
to turn your computer into a cash machine ! ! !
( available in the us and canada )
i earned $ 25 , 000 last month - send for my bank statements ! ! !
we are giving away a free , 3 - day vacation to all
folks who ask for more info on how to earn $ 1000
per sale simply by using their computer !
you ' ll earn $ 1000 per sale on a low cost product and
$ 3000 per business contact -
and all marketing is from the internet . free
sophisticated and duplicatable marketing system
( $ 2500 value ) is given to you gratis - as well as all
training and marketing support ! ! !
we invite you to explore , with no obligation , some
information that could turn around your
income and bring in thousands per week !
if you just want some extra income , or if you are a
seasoned marketer - our paint - by - numbers system with live
support ( up to 10 : 00 pm eastern every day ! ) will turn you
into a pro ! ! !
family - loved product ! ! !
we will have you in profit quick - and with
constant , live free support ! ! ! !
request more free info now -
send an email to : growthmarkets @ excite . com with " send info " in the subject line ! !
( do not click reply ! )
this email conforms to commercial email regulations within the us .
please send any " remove " requests to : growthmarkets @ excite . com
- - - -
this sf . net email is sponsored by : thinkgeek
welcome to geek heaven .
http : / / thinkgeek . com / sf
spamassassin - sightings mailing list

Subject: kime oy vereceksiniz ?
?yi g?nler
d?nya gazetesi , i?inde bulundu?umuz siyasi karma?a d?neminin se?imler sonras?nda nas?l bir hal alaca?? konusunda kapsaml? bir ara?t?rma yapmaktad?r . bu ?er?evede toplumumuzun m?mk?n oldu?unca geni? bir kesiminin g?r??lerine ba?vurmay? gerekli g?rd?k .
3 kas?m 2002 tarihinde yap?lmas? ?ng?r?len se?imler sonras?nda siyasi belirsizli?in , dolay?s?yla da ekonomik belirsizli?in sona erip ermeyece?i y?n?nde bir tahmin yapmam?z ve bu konuda kamuoyunu bilgilendirmemiz gerekti?ini d???n?yoruz . sizin de g?r??lerinizi bize iletmeniz anketin sa?l?kl? olmas? ?er?evesinde ?nem ta??maktad?r .
d?nya gazetesi , anketi cevaplayanlar?n kimlikleri konusunda herhangi bir a??klaman?n yap?lmayaca?? , sadece cevaplar?n?n dikkate al?naca?? y?n?nde tam garanti verir . ?lginiz i?in te?ekk?r eder , ?al??malar?n?zda ba?ar?lar dileriz .
anketin , daha geni? kapsaml? olmasi ve b?y?k kitlelere ula?abilmesi i?in ,
tan?d?klar?n?za bu mail ? i g?nderebilirsiniz .
soru 1
se?imde hangi partiye oy vermeyi d???n?yorsunuz ?
soru 2
sizce se?imlerde en ?ok oyu hangi partiler alacak , bir s?ralama yapabilir misiniz ?
soru 3
se?imlerin sonucunu etkileyebilecek temel geli?meler ne olabilir ?
d?nya gazetes? ankara tems?lc?l???
tel : 312 446 99 24
fax : 446 91 54
ankara @ dunyagazetesi . com . tr
- - - -
this sf . net email is sponsored by : thinkgeek
welcome to geek heaven .
http : / / thinkgeek . com / sf
spamassassin - sightings mailing list

Subject: i missed you 24632
if amateurs is what you want , then we have them .
take a look at these hardcore sites . young hottt teens ! ! !
these are the best of the best when it comes to amateurs .
don ' t believe me ? take a look for yourself .
amateur petite
- - - - - - - - - - - - - - - - - - - - - - -
all natural tight coeds ! ! !
petite natural breasted amateurs ! !
exclusive amateur xxx videos ! ! !
hundreds of exclusive petite amateur models ! !
click here to check out the action ! ! ! !
http : / / tour 2 . amateurpetite . com / ? 1087
http : / / tour 2 . amateurpetite . com / ? 1087
ample amateurs
- - - - - - - - - - - - - - - - - - -
breasts . women have them , men love them . and for some men ( and women ! ) that old adage
" the bigger the better " holds true ! and you ' ll find plenty to hold on to here - our stable of stacked
exclusive ample amateurs will make your mouth water and your hands tired just looking at them !
http : / / tour 2 . ampleamateurs . com / ? 1087
http : / / tour 2 . ampleamateurs . com / ? 1087
amateur smut
- - - - - - - - - - - - - - - - - -
the smuttiest xxx amateurs on the web ! ! !
real amateurs in explicit photo shoots
1 , 000 ' s of high quality smut pics ! ! !
pics of " the horny girl next door "
nasty amateurs gone wild ! ! !
http : / / tourl . amateursmut . com / ? 1087
http : / / tourl . amateursmut . com / ? 1087
to be taken off this mailing list , simply hit your
reply button and put " remove " anywhere in the subject .
Subject: re : systemworks clearance sale _ limited quantities _ only $ 29 . 99 tj
take
control of your computer with this top - of - the - line software !
norton
systemworks 2002 software suite
- professional edition -
includes
six - yes 6 !
- feature - packed utilitiesall for 1
special low
price of only
$ 29 . 99 !
this
software will : -
protect your computer from unwanted and hazardous viruses -
help secure your private valuable information - allow
you to transfer files and send e - mails safely -
backup your all your data quick and easily - improve your
pc ' s performance w / superior
integral diagnostics ! - you ' ll never have to take your
pc to the repair shop again !
6
feature - packed utilities
1
great price
a $ 300 +
combined retail value
yours for
only $ 29 . 99 !
price includes free
shipping ! and
for a limited time buy any 2 of our products get 1 free !
don ' t fall
prey to destructive viruses or hackers ! protect your computer and
your valuable information and
-
click here to order yours now ! -
or call
toll - free 1 - 800 - 861 - 1481 !
your email
address was obtained from an opt - in list . opt - in uefas ( united email
federation against spam ) approved list - purchase code #
8594030 . if you wish to be unsubscribed from this list , please click
here . if you have previously unsubscribed and are still receiving
this message , you may email our spam
abuse control center . we do not condone spam in any shape or form .
thank you kindly for your cooperation .

Subject: gov ' t guaranteed home business
wealth without risk ! ! !
discover the best kept secret in america !
turning $ 300 into $ 20 , 000
in oklahoma , craig
talkington purchased a tax lien on a 5 acre parcel for
$ 300 . the owner failed to pay the taxes and forfeited
the 5 - acre parcel to craig talkington . a short time
later craig sold that property to one of the neighbors
for $ 20 , 000 . that ' s the kind of money that buys new
cars and sends young people to college . craig didn ' t
stop at one deal . he later bought a tax lien for only
$ 17 on a ten acre track , the property owner failed to
pay the taxes , and craig ended up the property , which
he sold for $ 4 , 000 . i don ' t know how much money you
are making right now but these are the kinds of
profits that change peoples lives and solve financial
problems and make things a lot better .
janice knetzger turned a $ 463 . 00 investment into $ 65 , 000 . 00 !
wayne robertson paid $ 1 . 00 for a home !
todd beemer turned a $ 21 , 500 investment into $ 150 , 000 . 00 !
for serious investors and entrepreneurs only
for a
free
consultantion to see if you qualify
fill out
the no obligation form below for more
information .
required input field *
name
*
address
*
city
*
state
*
phone
*
email address
*
* all
tax liens and deeds directly support local
fire departments , police departments , schools ,
roads , and hospitals . thank you for your interest and
support .
to be removed , please
click here .
4589 dfsll - 151 rzeh 9359 iyoc 9 - 006 fl 29
Subject: ke casino spring fling competition : ) fre : rpvnltb
welcome to ms @ casino - a revolution in cyber gamlng !
ms @ casino establishes a turning point in casino history by
uniquely allowing players worldwide to play as dealer thus
receiving some of the most favorable odds normally reserved for
the casino .
ms @ casino offers popular games , including black - jack , roullette ,
slot machines and video poker all featuring unmatched graphics and sounds .
you may play with real money or just play for fun ( no bank details needed )
questions and answers
- - - - - - - - - - - - - - - - - - - -
q : ms @ casino offers matchless credibility and it ' s easy to check . how ?
a : robert as player and graham as dealer enter one of the games . once the game
is over , they verify that one ' s losing sum is the other ' s winning sum .
q : ms @ casino offers the highest payouts available . how is that possible ?
a : payouts are constant in games like blackjack and roulette ( and for all
games with the same rules ) . ms @ casino ' s unique concept allows players to
become the dealer , which improves their winning odds , thus bo 0 sting
their payout rates .
the top daily player ( determined at 23 : 59 ) gets $ 200 bonus !
winnings generated from playing as dealer are also accumulated .
the scoreboard will be updated every hour .
visit our site http : / / 4 highrollers . net - try your luck no deposit required !
best regards ,
virginia hancock
casino manager

Subject: how to soak her in cum
" i just wanted to write and thank you for spur - m .
i suffered from poor sperm count and motility . i found
your site and ordered spur - m fertility blend for men .
i have wondered for years what caused low semen and sperm
count , and how i could improve my fertility and help my wife
conceive . spur - m seems to have done just that ! thank you
for your support . "
andrew h . , london , uk
" spur - m really does help improve fertility and effectiveness
of sperm and semen motility . i used it for the past few months ,
and not only does it work - i also feel better to . i have
more energy . this is an excellent counter to low sperm count
and motility . i ' ll be buying more ! ! ! "
franz k . , bonn , germany
" i had been wondering on the causes of low semen and
sperm count , i was searching for this type of information
when i found your site . i hadn ' t been made aware of this
product before then , so was quite surprised to be able
to find a male fertility product . usually everything is
geared towards female fertility . suffice to say i ordered
and a few months later we received the good news from the
doctors - my wife is pregnant . i can ' t be 100 % sure if
it was spur - m that helped . but i am happy enough to be able
to say it should be considered by any man looking to increase
his fertility . it worked for me . thanks . "
roy b . , essex , uk
not interested in promotional campaign , go here
http : / / munoz . provencaux . net / rm . php
Subject: luv our rolexes for the same fea - tures and lovvprices .
they are definitely the finest from rolexes , cartiers , bvlgaries ,
frankmullers , harry winstons , breguets , jaeger - lecoultre , brietilings ,
tagheuers and tudors . first of all , their overall lo 0 ks are perfect .
secondly , vievv their details . every small logo and serial number shown
speak for their elegance .
you will also flnd out how ccheap our lovely goodss are . you might even
vvant 2 or 3 vvatches for your collections . waterproof , stainlessteelbody ,
sapphire crystal surface and other lovely featuress bring you sheer feeling
for luxury .
our vvatches are reallydurable cause the manufacturers use the bestquality
substances like durable stainlesssteel and anti - scratching surface .
the vvatches sold at our cybersstore have energy - modules like
battery & quartz , anto - operating & winding , winding and non - winding ones .
the classics have hack mechanism with stainlesssteelback . we have them .
their when you promised to go . "
" no , i did not promise . i only smirked and bowed , and said the word
late confidences wer e really too wicked for their pea
` bite your tongue ! ' said princess miaghkaia suddenly . ` karenina is a
splendid woman . i don ' t like her husband - but her i like very much . ' to
the window to recollect himself , and feel how he ought to behave .
ce of mind , some weath 1 erbeaten ragged old rooks ' - nests , 7 burdening
their hi gher branch
Subject: quarterly statement notice
security center
we recently noticed an attempt to log in to your paypal account from a
foreign ip address and we have reason to belive that your account was used
by a third party without your authorization .
if you recently accessed your account while traveling , the unusual log in attempts
may have been initiated by you .
therefore , if you are the rightful account holder , click on the link below to log into your account and follow the instructions . https : / / www . paypal . com / cgi - bin / webscr ? cmd = _ login - run
if you choose to ignore our request , you leave us no choice but to temporarily suspend
your account .
if you received this notice and you are not the authorized account
holder , please be aware that it is in violation of paypal policy to represent
oneself as another paypal user . such action may also be in violation of
local , national , and / or international law . paypal is committed to assist
law enforcement with any inquires related to attempts to misappropriate
personal information with the intent to commit fraud or theft .
information will be provided at the request of law enforcement agencies to
ensure that impersonators are prosecuted to the fullest extent of the law .
thank you for your patience as we work together to protect your account .
sincerely ,
paypal account review department
paypal , an ebay company
* please do not respond to this e - mail as your reply will not be received .

Subject: update your online banking records
notification of limited account access
as part of our security measures , we regularly screen activity in the
banking system .
we recently noticed the following issue on your account :
we would like to ensure that your account was not accessed by an
unauthorized third party . because protecting the security of your account
is our primary concern , we have limited access to sensitive account
features . we understand that this may be an inconvenience but please
understand that this temporary limitation is for your protection .
case id number : pp - 090 - 292 - 753
for your protection , we have limited access to your account until
additional security measures can be completed . we apologize for any
inconvenience this may cause .
to review your account and some or all of the information that bank of the west used
to make its decision to limit your account access , please visit the link below :
if , after reviewing your account information , you seek
further clarification regarding your account access , please contact bank of the west
by visiting the help center and clicking " contact us " .
we thank you for your prompt attention to this matter . please understand
that this is a security measure intended to help protect you and your
account . we apologize for any inconvenience .
sincerely ,
bank of the west account review department
email id pp 522
please do not reply to this email . this mailbox is not monitored and you will not receive a response .

Subject: 00971 50 2443308 kevin contact me
hello ,
how are you doing with the entire member of your family ?
i believed that you will be in better position to corporate with me hence you have vast knowledge in the field of international transaction and investment . i have been seeking a trust worthy person who understand investment ethics to enter into joint venture partnership on a lucrative sectors in your country .
my name is mr . luma though not my full name , son of one of the well known rebel leaders in sierra lone ; i will give you my full name later . i am in a hide out now in a country in u . a . e dubai due to recent dead of my father in prison . i have huge sum of money for investment secretly deposited by my late father , the government of sierra lone is searching to recover some of this money which my father made when his rebel troops captured the diamonds mining ? s field in sierra lone .
the money is in millions of u . s . dollars ( us 25 . 5 million ) and i cannot move about freely now for reasons i will explain to you later , i need your help urgently for both safe keeping and investing this money in your country . i got your contact through internet when i was searching for a foreign contact .
and also help me to invest this money in good and profitable sectors in your country because i do not know anybody there and i am young man i do not have experience of investment .
i will be very grateful for your urgent response while hoping to do good investments with you on life time ventures .
my best regards .
mr . kevin .
Subject: logo , stationer , website design and so much more !
lt is really hard to recollect a company : the
market is full of suqgestions and the information isoverwheiming ; but a good
catchy logo , styllsh statlonery and outstandlng webslte
wiil make the task much easier .
we do not promise that having ordered a iogo your
company wili automaticaily become a world ieader : it isguite clear that
without qood products , effective business organization and practicable aim it
will be hotat nowadays market ; but we do promise that your marketing efforts
will become much more effective . here is the list of clear
benefits : creativeness : hand - made , original logos , specially done
to reflect your distinctive company image . convenience : logo and stationery
are provided in all formats ; easy - to - use content management system letsyou
change your website content and even its structure . promptness : you
will see logo drafts within three business days . affordability : your
marketing break - through shouldn ' t make gaps in your budget . 100 % satisfaction
guaranteed : we provide unlimited amount of changes with no extra fees for you to
be surethat you will love the result of this collaboration . have a look at our
portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ not interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Subject: naturally irresistible your corporate identity
lt is really hard to recollect a company : the
market is full of suqgestions and the information isoverwheiming ; but a good
catchy logo , styllsh statlonery and outstandlng webslte
wili make the task much easier .
we do not promise that having ordered a ioqo your
company will automatically become a worid leader : it isquite ciear that
without good products , effective business organization and practicable aim it
will be hotat nowadays market ; but we do promise that your marketing efforts
will become much more effective . here is the list of clear
benefits : creativeness : hand - made , original logos , specially done
to reflect your distinctive company image . convenience : logo and stationery
are provided in all formats ; easy - to - use content management system letsyou
change your website content and even its structure . promptness : you
will see logo drafts within three business days . affordability : your
marketing break - through shouldn ' t make gaps in your budget . 100 % satisfaction
guaranteed : we provide unlimited amount of changes with no extra fees for you to
be surethat you will love the result of this collaboration . have a look at our
portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ not interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Subject: restore your access
security
assistance
it has come to our attention that your account information needs to be
updated as part of our continuing commitment to protect your account and to
reduce the instance of fraud on our website . just update your personal records and you will not run into
any future problems with the online service .
however , failure to update your records until july . 21 , 2005 your account considered as suspension .
please update your records as soon as this email being sent .
our system requires further account
verification .
case id number : pp - 563 - 002 - 410
once you have updated your account records , your session will not be
interrupted and will continue as normal .
as
soon as possible . allowing your account access to remain
limited for an extended period of
time may result in further limitations on
the use of your account and possible account
closure .
click here to update your
account
you can
also confirm your identity by logging into your paypal account
at https : / / www . paypal . com / us / .
and you will be directed to the verifying page .
thank you for using paypal !
the paypal team
please do
not reply to this e - mail . mail sent to this address cannot be
answered unscribe - mailing @ paypal . com . opt : in , opt : out for assistance ,
log
in
to your paypal account and choose the " help " link in the footer of
any page .
to receive email notifications in plain text
instead of html , update
your preferences here .
paypal email id pp 468

Subject: failure notice
hi . this is the qmail - send program at mail . globalhosting . com .
i ' m afraid i wasn ' t able to deliver your message to the following addresses .
this is a permanent error ; i ' ve given up . sorry it didn ' t work out .
:
sorry , no mailbox here by that name . vpopmail ( # 5 . 1 . 1 )
- - - enclosed are the original headers of the message .
content - type : message / rfc 822
return - path :
received : ( qmail 93914 invoked by uid 399 ) ; 19 jul 2005 11 : 18 : 55 - 0000
received : from unknown ( helo ml . dnsix . com ) ( 63 . 251 . 171 . 164 )
by mail . globalhosting . com with smtp ; 19 jul 2005 11 : 18 : 55 - 0000
received : from [ 61 . 106 . 118 . 27 ] ( helo = mailwisconsin . com )
by ml . dnsix . com with smtp ( exim 4 . 44 )
id ldupnn - 0002 ud - uo
for distltmich @ compusep . com ; tue , 19 jul 2005 03 : 58 : 20 - 0700
received : from 205 . 214 . 42 . 66
( squirrelmail authenticated user projecthoneypot @ projecthoneypot . org ) ;
by mailwisconsin . com with http id j 87 gzo 38191009 ;
tue , 19 jul 2005 10 : 57 : 46 + 0000
message - id :
date : tue , 19 jul 2005 10 : 57 : 46 + 0000
subject : just to her . . .
from : " barry castillo "
to : distltmich @ compusep . com
user - agent : squirrelmail / 1 . 4 . 3 a
x - mailer : squirrelmail / 1 . 4 . 3 a
mime - version : 1 . 0
content - type : text / html ; charset = iso - 8859 - 1
content - transfer - encoding : 8 bit
x - priority : 3 ( normal )
importance : normal
( body supressed )

Subject: failure notice
hi . this is the qmail - send program at backup - smtp - 2 . star . net . uk .
i ' m afraid i wasn ' t able to deliver your message to the following addresses .
this is a permanent error ; i ' ve given up . sorry it didn ' t work out .
:
81 . 171 . 128 . 25 does not like recipient .
remote host said : 550 , recipient unknown
giving up on 81 . 171 . 128 . 25 .
- - - below this line is a copy of the message .
return - path :
received : ( qmail 28287 invoked from network ) ; 19 jul 2005 10 : 58 : 25 - 0000
received : from catv - 219 - 099 - 025 - 107 . medias . ne . jp ( helo mailwisconsin . com ) ( 219 . 99 . 25 . 107 )
by backup - smtp - 2 . star . net . uk with smtp ; 19 jul 2005 10 : 58 : 25 - 0000
received : from 205 . 214 . 42 . 66
( squirrelmail authenticated user projecthoneypot @ projecthoneypot . org ) ;
by mailwisconsin . com with http id j 87 gzo 38191062 ;
tue , 19 jul 2005 10 : 57 : 46 + 0000
message - id :
date : tue , 19 jul 2005 10 : 57 : 46 + 0000
subject : just to her . . .
from : " barry castillo "
to : distinctively @ hamilton - school . co . uk
user - agent : squirrelmail / 1 . 4 . 3 a
x - mailer : squirrelmail / 1 . 4 . 3 a
mime - version : 1 . 0
content - type : text / html ; charset = iso - 8859 - 1
content - transfer - encoding : 8 bit
x - priority : 3 ( normal )
importance : normal
soft viagra at $ 1 . 62 per dose
ready to boost your sex life ? positive ?
time to do it right now !
order soft viagra at incredibly low prices
startinq at $ 1 . 99 per dose ! unbelivable !
Subject: failure notice
hi . this is the qmail - send program at mail . bmadesign . com .
i ' m afraid i wasn ' t able to deliver your message to the following addresses .
this is a permanent error ; i ' ve given up . sorry it didn ' t work out .
:
sorry , no mailbox here by that name . vpopmail ( # 5 . 1 . 1 )
- - - below this line is a copy of the message .
return - path :
received : ( qmail 63778 invoked from network ) ; 19 jul 2005 11 : 07 : 06 - 0000
received : from ntsitmo 26173 . sitm . nt . adsl . ppp . infoweb . ne . jp ( helo mailwisconsin . com ) ( 218 . 217 . 148 . 173 )
by mail . bmadesign . com with smtp ; 19 jul 2005 11 : 07 : 06 - 0000
received : from 205 . 214 . 42 . 66
( squirrelmail authenticated user projecthoneypot @ projecthoneypot . org ) ;
by mailwisconsin . com with http id j 87 gzo 38190336 ;
tue , 19 jul 2005 10 : 57 : 46 + 0000
message - id :
date : tue , 19 jul 2005 10 : 57 : 46 + 0000
subject : just to her . . .
from : " barry castillo "
to : distinctionsemienw @ bmadesign . com
user - agent : squirrelmail / 1 . 4 . 3 a
x - mailer : squirrelmail / 1 . 4 . 3 a
mime - version : 1 . 0
content - type : text / html ; charset = iso - 8859 - 1
content - transfer - encoding : 8 bit
x - priority : 3 ( normal )
importance : normal
soft viagra at $ 1 . 62 per dose
ready to boost your sex life ? positive ?
time to do it right now !
order soft viagra at incredibly low prices
startinq at $ 1 . 99 per dose ! unbelivable !
'''

In [221]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag

In [29]:
import stanza

nlp = stanza.Pipeline(lang='en', processors='tokenize,ner')
#print(*[f'token: {token.text}\tner: {token.ner}' for sent in doc.sentences for token in sent.tokens], sep='\n')

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.4.0.json:   0%|   â€¦

2022-08-21 12:16:16 INFO: Loading these models for language: en (English):
=========================
| Processor | Package   |
-------------------------
| tokenize  | combined  |
| ner       | ontonotes |
=========================

2022-08-21 12:16:16 INFO: Use device: cpu
2022-08-21 12:16:16 INFO: Loading: tokenize
2022-08-21 12:16:16 INFO: Loading: ner
2022-08-21 12:16:17 INFO: Done loading processors!

In [106]:
rt = nlp(raw_text)

In [116]:
#print(*[f'token: {token.text}\tner: {token.ner}' for sent in rt.sentences for token in sent.tokens], sep='\n')

In [32]:
w = []
t = []
for sent in rt.sentences:
    for token in sent.tokens:
        w.append((token.text))
        t.append((token.ner))

In [54]:
data = {'words':w, 'labels': t}
df2 = pd.DataFrame(data)
df2.head(10)

     words labels
0  Subject      O
1        :      O
2     attn      O
3        :      O
4        i      O
5  presume      O
6     this      O
7     mail      O
8     will      O
9      not      O

In [126]:
from spacy.tokens import Doc

In [131]:
import spacy
nlp = spacy.load("en_core_web_sm")
rt = nlp(raw_text)

In [134]:
assert rt.has_annotation("SENT_START")

In [136]:
doc = list(rt.sents)

In [179]:
dframcy = DframCy(nlp)
spacy_df = dframcy.to_dataframe(rt, ['is_sent_start', 'id', 'text', ]).reset_index()
spacy_df.token_is_sent_start = spacy_df.token_is_sent_start.astype(bool).cumsum() - 1
spacy_df = spacy_df.rename(columns={'token_is_sent_start': 'sentence_id',
                                    'token_text': 'Words', })

In [180]:
data.head()

    sentence_id          words  POS labels
0             0      Thousands  NNS      O
1             0             of   IN      O
2             0  demonstrators  NNS      O
3             0           have  VBP      O
4             0        marched  VBN      O
5             0        through   IN      O
6             0         London  NNP  B-GEO
7             0             to   TO      O
8             0        protest   VB      O
9             0            the   DT      O
10            0            war   NN      O
11            0             in   IN      O
12            0           Iraq  NNP  B-GEO
13            0            and   CC      O
14            0         demand   VB      O
15            0            the   DT      O
16            0     withdrawal   NN      O
17            0             of   IN      O
18            0        British   JJ  B-GPE
19            0         troops  NNS      O
20            0           from   IN      O
21            0           that   DT      O
22            0        country   NN      O
23            0              .    .      O
24        11111       Families  NNS      O
25        11111             of   IN      O
26        11111       soldiers  NNS      O
27        11111         killed  VBN      O
28        11111             in   IN      O
29        11111            the   DT      O

In [182]:
spacy_df["sentence_id"] = LabelEncoder().fit_transform(spacy_df["sentence_id"] )
spacy_df

      index  sentence_id        Words
0         0            0           \n
1         1            0      Subject
2         2            0            :
3         3            0         attn
4         4            0            :
...     ...          ...          ...
7635   7635          593         dose
7636   7636          593            !
7637   7637          594  unbelivable
7638   7638          594            !
7639   7639          594           \n

[7640 rows x 3 columns]

In [184]:
spacy_df = spacy_df.drop(axis=1, columns=['index'])

In [186]:
result = pd.concat([df2, spacy_df], axis=1, join='inner')
display(result)

            words labels  sentence_id    Words
0         Subject      O            0       \n
1               :      O            0  Subject
2            attn      O            0        :
3               :      O            0     attn
4               i      O            0        :
...           ...    ...          ...      ...
7021          per      O          537        :
7022         dose      O          537       58
7023            !      O          537        :
7024  unbelivable      O          537       25
7025            !      O          537        -

[7026 rows x 4 columns]

In [188]:
result= result.drop(columns=['Words'])

In [208]:
new_col = ['sentence_id', 'words', 'labels']
result=result.reindex(columns=new_col)

   sentence_id    words labels
0            0  Subject      O
1            0        :      O
2            0     attn      O
3            0        :      O
4            0        i      O

In [212]:
result1=data.drop(columns=['POS'])

   sentence_id          words labels
0            0      Thousands      O
1            0             of      O
2            0  demonstrators      O
3            0           have      O
4            0        marched      O

In [213]:
frames = [result1, result]
  
fdf = pd.concat(frames)
display(fdf)

      sentence_id          words labels
0               0      Thousands      O
1               0             of      O
2               0  demonstrators      O
3               0           have      O
4               0        marched      O
...           ...            ...    ...
7021          537            per      O
7022          537           dose      O
7023          537              !      O
7024          537    unbelivable      O
7025          537              !      O

[1055601 rows x 3 columns]

In [214]:
X= fdf[["sentence_id","words"]]
Y =fdf["labels"]

In [215]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size =0.2)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=1)

In [216]:
#building up train data and test data
train_data = pd.DataFrame({"sentence_id":x_train["sentence_id"],"words":x_train["words"],"labels":y_train})
test_data = pd.DataFrame({"sentence_id":x_test["sentence_id"],"words":x_test["words"],"labels":y_test})
val_data = pd.DataFrame({"sentence_id":x_val["sentence_id"],"words":x_val["words"],"labels":y_val})

In [218]:
args = NERArgs()
args.num_train_epochs = 1
args.learning_rate = 1e-4
args.overwrite_output_dir =True
args.train_batch_size = 32
args.eval_batch_size = 32

In [219]:
model = NERModel('bert', 'bert-base-cased',labels=label,args =args, use_cuda=torch.cuda.is_available())

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForTokenClassification: ['cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForTokenClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [220]:
model.train_model(train_data,eval_data = val_data,acc=accuracy_score)

  0%|          | 0/13 [00:00<?, ?it/s]

C:\Users\ASUS\anaconda3\lib\site-packages\transformers\optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 0 of 1:   0%|          | 0/1499 [00:00<?, ?it/s]

(1499, 0.22101658301861624)

In [222]:
result, model_outputs, preds_list = model.eval_model(test_data)

  0%|          | 0/13 [00:00<?, ?it/s]

Running Evaluation:   0%|          | 0/1460 [00:00<?, ?it/s]

In [223]:
result

{'eval_loss': 0.16719164875757,
 'precision': 0.8275506698728959,
 'recall': 0.7674174126341945,
 'f1_score': 0.7963504735458917}

In [226]:
prediction, model_output = model.predict(["My name is Sugam. I work at Annex computers. I live in Ludhiana."])

  0%|          | 0/1 [00:00<?, ?it/s]

Running Prediction:   0%|          | 0/1 [00:00<?, ?it/s]

In [227]:
prediction

[[{'My': 'O'},
  {'name': 'O'},
  {'is': 'O'},
  {'Sugam.': 'B-PER'},
  {'I': 'O'},
  {'work': 'O'},
  {'at': 'O'},
  {'Annex': 'B-ORG'},
  {'computers.': 'O'},
  {'I': 'O'},
  {'live': 'O'},
  {'in': 'O'},
  {'Ludhiana.': 'B-GEO'}]]